name: First workflow

on: workflow_dispatch

jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello Abhishek"
      
      - name: Print goodBye
        run: echo "Done Bye"

